### ISSUE TITLE
Override the theme settings

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo-theme-landscape#102]
Hello,
In my _config.yml I can override the menu settings but not the sidebar parameter.
Has the override limitations for this theme ?

**Comment by tomap** [comment]
Can you rephrase the question and explain what you want to do, not what you want to override?
Do you want to hide the sidebar?

**Comment by M1ke** [comment]
I have the same issue. I have added the following in `_config.yml`:

```
theme_config:
  twitter: https://twitter.com/m1ke
  widgets:
  - tagcloud
  - recent_posts
  menu:
    About: /about/
```

The menu correctly updates to show `about/` (though this doesn't actually hide Home & Archives) but the sidebar shows all widgets and Twitter link doesn't show. So it seems not all theme values can be overridden.
