### ISSUE TITLE
Embeded gist unreadable

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo-theme-landscape#160]
I found the following styles are applied to `{% gist %}` tag plugin (with default landscape theme)

``` css
.article-entry .gist {
  margin: 0 -20px;
  border-style: solid;
  border-color: #ddd;
  border-width: 1px 0;
  background: #2d2d2d;
  padding: 15px 20px 15px 0;
}
```

```
{% gist 7071963 %}
```

The negative margin make no space between the text and the container.
Also, the dark background make it difficult to read the text.
"misc" and "history" header in the gist is barely readable.
![selection_007](https://cloud.githubusercontent.com/assets/544400/5241962/18bc78b2-7964-11e4-9d03-73cbbc278d29.png)

Is there any reason for the current `.article-entry .gist` sytle?
