### ISSUE TITLE
how to disable landscape theme?

### ISSUE THREAD

**Issue by cleechtech** [hexojs/hexo-theme-landscape#45]
I tried setting `theme: false` in my **_config.yml** but the landscape theme still shows up. How can I disable theming for my hexo blog?

**Comment by Xuanwo** [comment]
Post your `_config.yml` here.

**Comment by cleechtech** [comment]
Steps to reproduce:

```
$ hexo version
hexo-cli: 0.1.8
os: Darwin 15.2.0 darwin x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
$ hexo init disable-landscape
$ cd disable-landscape
$ npm i
```

Change line 66 of **_config.yml** (to theme: false):

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:
```

Run `$ hexo server`. On localhost:4000 the landscape theme still appears. `hexo clean` does not fix.
